cloud-bulldozer/performance-dashboards

templates/ocp-performance.jsonnet
=> Add multi option to infra and worker nodes

templates/ocp-performance.jsonnet
This commit adds panels for the following metrics:
- Cluster operators information including count, conditions - operators
in degraded and progressing state.
- Services and routes count.
=> Add cluster operators panel and more metrics

templates/ocp-performance.jsonnet
This PR adds two functions that reduce the code significantly since they avoid some code duplication:
- genericGraphPanel: 
- genericGraphLegendPanel
Both functions have the parameter `sort='decreasing'` required to sort the tooltip.
=> Sort tooltip and optimizations for OCP dashboard

templates/ocp-performance.jsonnet
Add container writes panel for master nodes.
Also fix query from pod count stat panel.
=> Container writes panel

dittybopper/templates/dittybopper.yaml.template
This is a fix until grafana pushes official images
https://github.com/grafana/grafana/issues/27677
=> User image from quay.io

templates/etcd-on-cluster-dashboard.jsonnet, templates/ocp-performance.jsonnet
A bunch of improvements to the etcd dashboard:
- Add units
- New DB size graph panel
- Sort tooltips
- Add legend
- Unify networking rx/tx panels
- Fix CPU panel
=> Etcd dashboard improvements

dittybopper/k8s-deploy.sh, dittybopper/templates/k8s-dittybopper.yaml.template, templates/k8s-perf.jsonnet
Previous work was centered totally around OpenShift. This works with k8s
deployments I have around (EKS and GKE).
If we feel I should collapse the deploy script into the existing one, that should be possible, just didn't want to break existing functionality.
=> Adding k8s template and deployment mechanism

templates/k8s-perf.jsonnet
- Lots of variables needed to be fixed or removed.
- Updated the panels
- Removed some panels that are unused for raw k8s
=> Fixing the k8s template

templates/ocp-performance.jsonnet
Enhances existing OVN queries.
=> Improve OVN queries

dittybopper/deploy.sh, dittybopper/templates/dittybopper.yaml.template, templates/etcd-on-cluster-dashboard.jsonnet, templates/hypershift-performance.jsonnet
Included a new jsonnet template for populating hypershift dashboard with HostedControlPlane components.
Out - https://snapshots-origin.grafana.net/dashboard/snapshot/qAkJgcT651y4i2Ke5eeY6AIXKPJVbwM6?orgId=2
=> New Dashboard for hypershift components

templates/ocp-performance.jsonnet
=> Sum by pod for OVN CNI metrics

dittybopper/deploy.sh, templates/ovn-dashboard.jsonnet
Dedicated dashboard to monitor OVN metrics, still there are issue with metric collection and being fixed so this PR will get updated if anything changes.
- Resource monitoring
- Creation Latency monitoring
- Processing Queue monitoring
=> OVN dashboard

templates/cilium-k8s-perf.jsonnet
=> Cilium cluster dash

.github/workflows/release.yml, Makefile, dittybopper/syncer/Dockerfile, dittybopper/syncer/entrypoint.sh
Simplify Dockerfile to support multiarch builds
=> Support multi-arch builds

Makefile
=> Missing archs

dittybopper/deploy.sh, dittybopper/k8s-deploy.sh, dittybopper/templates/dittybopper.yaml.template, dittybopper/templates/k8s-dittybopper.yaml.template
Need to add in an option to set grafana quay image from environment variable. This will help with adding url's specific to arm architecture types
=> Parameterized grafana image

LICENSE
Add License file
This commit proposes an Apache v2 license. Need ack from all current contributors.
#46
=> Add Apache v2 license

dittybopper/deploy.sh, dittybopper/k8s-deploy.sh, dittybopper/templates/dittybopper.yaml.template, dittybopper/templates/k8s-dittybopper.yaml.template
Allow dittydopper to be deployed in user-specific namespaces.
Signed-off-by: Krishna Harsha Voora <krvoora@redhat.com>
=> Allows dittybopper to be deployed in user-specified namespaces

.github/workflows/ci.yml, .github/workflows/grafana.yml
This PR allows insecure connection establishment, thus allowing
this workflow to complete successfully
Signed-off-by: Krishna Harsha Voora <krvoora@redhat.com>
=> Fix GHA: Grafana Importer issues

dittybopper/README.md, dittybopper/deploy.sh, dittybopper/k8s-deploy.sh
* Removes `jq` dependency
* updates README.md
#38
=> Remove jq's dependency

README.md, templates/ovn-dashboard.jsonnet
This PR adds a new metric, to understand duration for OVN to apply
network configurations
Signed-off-by: Krishna Harsha Voora <krvoora@redhat.com>
=> Updates to OVN & README.md

templates/ocp-performance.jsonnet
- Adding Stackrox namespace/project
- Adding some Stackrox specific queries
Signed-off-by: Joe Talerico (rook) <joe.talerico@gmail.com>
=> Adding Stackrox specific metrics

templates/ocp-performance.jsonnet
Irate is more accurate on fast-changing metrics like CPU usage
=> Replace rate by irate in CPU related graphs

templates/ocp-performance.jsonnet
Used memory = total memory - free - buffers - cache
=> Plot used memory and not just "Active" memory

dittybopper/deploy.sh
=> Fix dittybopper-syncer image location

dittybopper/syncer/entrypoint.py
Fixing null pointer exception. When we have empty tags, syncer ends up adding null as tags which leads to errors while rendering settings page of dashboard. This PR handles that corner case and fixes the issue.
Deployed dittybopper in local and verified if the settings page is properly rendering for the dashboards.
=> NPE fix in case of no tags

dittybopper/syncer/entrypoint.py
Fixing tags that weren't in list format previously in dashboard json.
Tested in local by verified in the tags being populated in k8s-netperf dashboard.
=> bug fix in tags list

dittybopper/deploy.sh
This PR makes the following changes:
- Fixes bug introduced in #87 preventing custom dashboard imports
- Adds additional debugging for dashboard imports
- Some general cleanup
Slack Thread: https://redhat-internal.slack.com/archives/GTHU29259/p1704222045916509
See this Jenkins job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/470/console
=> Fixes and additional debugging for dittybopper deploy script

assets/ycsb/panels.libsonnet, assets/ycsb/queries.libsonnet, assets/ycsb/variables.libsonnet, templates/General/ycsb-v2.jsonnet
Adding YCSB Dashboard to grafonnet
- Closes #
=> Adding YCSB Dashboard to grafonnet.

assets/pgbench-dashboard/annotation.libsonnet, assets/pgbench-dashboard/panels.libsonnet, assets/pgbench-dashboard/queries.libsonnet, assets/pgbench-dashboard/variables.libsonnet, templates/General/pgbench-dashboard-v2.jsonnet
Adding pgbench dashboard to grafonnet.
- Closes #
=> Adding pgbench dashboard to grafonnet.

README.md, assets/hypershift-perf-dashboard/panels.libsonnet, assets/hypershift-perf-dashboard/queries.libsonnet, assets/hypershift-perf-dashboard/variables.libsonnet, templates/General/hypershift-performance-v2.jsonnet
Adding Hyepershift Performance Dashboard to Grafonnet
- Closes #
=> Adding Hyepershift Performance Dashboard to Grafonnet

.github/workflows/ci.yml
The assets dir should be included in gh actions paths
=> Include assets in gh actions

assets/kube-burner-report-mode/variables.libsonnet, assets/kube-burner-report-ocp-wrapper/variables.libsonnet
Discard garbage-collection jobs from selector.
=> Discard garbage-collection jobs from selector
