templates/ocp-performance.jsonnet

Makes things much more readable

K8s name rather than the container engine one

---

templates/etcd-on-cluster-dashboard.jsonnet

This addresses issue #2 
It uses the prometheus calls from https://github.com/tkashem/dittybopper/blob/dashboard/dashboards/etcd-overview.json as requested in the issue.
I positioned the data in a way that seemed logical, though I can easily move them.
Here are the pictures from a test aws cluster:

Improve etcd dashboard

---

dittybopper/deploy.sh

This commit will make sure the latest version of the dashboards are deployed
and also supports the case where user wants to redeploy dittybopper without
having to delete the namespace manually.

Delete the namespace if it already exists

---

templates/etcd-on-cluster-dashboard.jsonnet

Use irate for latency metrics (Will allow us to detect latency spikes that might be lead to a leader change), and replace rate by delta in slow ops queries.

Etcd improvements

---

templates/ocp-performance.jsonnet

Signed-off-by: Kedar Vijay Kulkarni <kkulkarni@redhat.com>
Looking at one of the dashboards perf team had put here [1] I saw we could add status to "Number of nodes" dashboard. It is useful.
Enhances jsonnet template to add that target. Tested with `make` and it rendered error-free.
[1]https://snapshot.raintank.io/dashboard/snapshot/y0xshWE8J42Fh1YaytIPheOT1nSLjRId?orgId=2&var-datasource=Cluster%20Prometheus&var-_worker_node=ip-10-0-111-23.us-west-2.compute.internal&var-_infra_node=ip-10-0-152-212.us-west-2.compute.internal&var-namespace=All&var-block_device=All&var-net_device=All&var-interval=2m
cc: @chaitanyaenr @jtaleric @mffiedler

Adding status to number of nodes dashboard

---

templates/ocp-performance.jsonnet

The current metric shown by this panel is misleading, let's just use the OOTB metric.
Also updating namespace count query since that metric is no longer being scraped in OpenShift.

Mem available

---

dittybopper/deploy.sh

Change in `grafana-datasources` secret in release 4.10, has `.datasources[0].secureJsonData.basicAuthPassword` instead of `.datasources[0].basicAuthPassword` 
4.7 got 
```
{
"apiVersion": 1,
"datasources": [
{
"access": "proxy",
"basicAuth": true,
"basicAuthPassword": "<secret>",
"basicAuthUser": "internal",
"editable": false,
"jsonData": {
"tlsSkipVerify": true
},
"name": "prometheus",
"orgId": 1,
"type": "prometheus",
"url": "https://prometheus-k8s.openshift-monitoring.svc:9091",
"version": 1
}
]
}
```
4.10 got this,
```
{
"apiVersion": 1,
"datasources": [
{
"access": "proxy",
"basicAuth": true,
"secureJsonData": {
"basicAuthPassword": "<secret>"
},
"basicAuthUser": "internal",
"editable": false,
"jsonData": {
"tlsSkipVerify": true
},
"name": "prometheus",
"orgId": 1,
"type": …
```

secret key change in 4.10

---

templates/ocp-performance.jsonnet

`irate` is more [precise](https://snapshots-origin.grafana.net/dashboard/snapshot/8dTBVRQdFM7gEDe1E4aMOogp7MAoeSR6?viewPanel=6&orgId=2) for cpu counter metrics than `rate` - https://prometheus.io/docs/prometheus/latest/querying/functions/#irate
[kube-burner](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/kube-burner/metrics-profiles/metrics.yaml#L22) uses `irate` as well for container cpu usage.

changing `rate` to `irate` for container cpu metric

---

templates/ocp-performance.jsonnet

Using buckets we can track the 99% of addlogicalport and ADD CNI
requests.

Use buckets for OVN metrics

---

Makefile
dittybopper/README.md
dittybopper/deploy.sh
dittybopper/syncer/Dockerfile
dittybopper/syncer/entrypoint.sh
dittybopper/templates/dittybopper.yaml.template
dittybopper/templates/k8s-dittybopper.yaml.template

This PR successfully makes it so the dashboard templates are loaded into the syncer image, so that they can be deployed at runtime without cloning this repository.
The downside to this change is the syncer image needs to be updated for each PR, so that must be setup on quay.io

Disconnected support

---

.github/workflows/syncer.yml

This PR adds an action to load the kube burner dashboard to the internal grafana. The Grafana URL is stored in the secret GRAFANA_URL, with the format "http://user:pass@url.goes.here.org:port". The secret should be set before this PR is merged.
It is run on commits pushed to the master branch.
I tested this on my own grafana instance deployed with dittybopper on an aws openshift cluster.

Action to load dashboard to grafana

---

.github/workflows/grafana.yml
.github/workflows/release.yml

The latest setup requires a new image for each change in the dashboards. This action is used to automatically build and push the image to the organization's quay.io.
For now it is limited to amd64 due to the use of an amd64 jsonnet binary download.

Quay Image Build and Push

---

templates/hypershift-performance.jsonnet

This commit adds the following metrics to help with understanding
the state and impact on the cluster during chaos testing:
- Cluster operators information (list and degraded state )
- Alerts ( severity = all except none )
- Etcd metrics focusing on Management Cluster ( openshift-etcd ns )
- Current node count with condition
- Namespace count ( hosted clusters control plane is hosted in ns )
- Pod count and Failed pods ( namespace/pod: phase )
- API 99th percentile latency with resource and namespace to understand
the component that's impacting the latency
- Top 10 CPU/Mem components on the management cluster

Expand HyperShift Management cluster metrics

---

templates/ocp-performance.jsonnet

Including a `min` field in the legend table will be useful to find the least value of a duration.
For ex, to get the least `idle` cpu of a node or least `available` memory during a period.

min of selected metrics in legend box

---

dittybopper/deploy.sh
dittybopper/templates/dittybopper_ns.yaml.template

Needed to add a way to label the created namespace with privileges and change the way the prometheus token is obtained 
```
% ./deploy.sh
____  _ __  __        __
/ __ \(_) /_/ /___  __/ /_  ____  ____  ____  ___  _____
/ / / / / __/ __/ / / / __ \/ __ \/ __ \/ __ \/ _ \/ ___/
/ /_/ / / /_/ /_/ /_/ / /_/ / /_/ / /_/ / /_/ /  __/ /
/_____/_/\__/\__/\__, /_.___/\____/ .___/ .___/\___/_/
/____/           /_/   /_/
Using k8s command: oc
Using namespace: dittybopper
Using default grafana password: admin
Getting environment vars...
Prometheus URL is: https://prometheus-k8s-openshift-monitoring.apps.**.qe.devcluster.openshift.com
Prometheus bearer token collected.
Creating namespace...
Looks like the namespace dittybopper already exists, deleting it
namespace "dittybopper" deleted …
```

Adding create token type and privileged namespace

---

templates/ovn-dashboard.jsonnet

This PR adds a new metric, to understand duration for OVN node to get to a ready state.

Added node ready latency metric and used corrected formatting

---

templates/ocp-performance.jsonnet

/cc @qiliRedHat 
I'm not sure it is worth it, but if we want to keep this chart in the future, this is the change I did for https://issues.redhat.com/browse/OCPBUGS-2637
We might want to monitor other mount points as well maybe.

Adds a panel with the inodes usage in /var/run/crio

---

dittybopper/deploy.sh

This fix is needed to be able to deploy the dittybopper dashboards from anywhere and not have a hard coded location

Adding bash localization

---

dittybopper/deploy.sh

If a cluster is up for longer than 6h, the token needs to be refreshed.
I see the expiration as unnecessary maintenance overhead.

Remove prometheus token duration

---

dittybopper/deploy.sh

1 hour after deploying dittybopper, the dashboards can not be displayed because of 'Forbidden'. Checked the token created by deploy.sh, it was already expired. Redeploy can fix the issue but it will come back again 1 hour later.
Create a  new token with `oc create token`, check the exp time, it's 1 hour after creation.
iat: 1677053861 2/22/2023, 1:47:41 PM
nbf: 1677053861 2/22/2023, 1:47:41 PM
exp: 1677057461 2/22/2023, 2:47:41 PM
Increase token expire time to 240h to avoid token expire during test.

increase token expire time

---

Makefile
dittybopper/deploy.sh
dittybopper/templates/dittybopper.yaml.template
templates/hypershift-performance.jsonnet
templates/ocp-performance.jsonnet

- Add OBO endpoint
- Modify regexp on hypershift dashboard to correct namespace names
- Fix some graphs on hypershift dashboards, pointing to incorrect namespaces
- On hypershift dashboard, using Prometheus Endpoint for Management Metrics and OBO for Hypershift ones
-  Add graphs for CPU and Mem for OBO and hypershift on the management side, and top10 CPU & Mem on Hosted Clusters Control Plane
- Correct indentation of namespace parameter on ocp objects causing `Warning: unknown field "namespace"`

Adapt hypershift dashboard to management clusters

---

templates/etcd-on-cluster-dashboard.jsonnet
templates/hypershift-performance.jsonnet
templates/ovn-dashboard.jsonnet

Some dashboard improvements:
- Replace 1m by 2m. As the default scrape interval is 30s, the minimum range should be 4x times that interval
- Remove pod variable from the etcd/hypershift dashboard, this variable is useless, there're only 3 etcd pods
- Update deprecated metric names etcd_debugging_mvcc_put_total/etcd_debugging_mvcc_delete_total

Dashboard improvements

---

.github/workflows/ci.yml
Makefile
dittybopper/deploy.sh
dittybopper/k8s-deploy.sh

- Updated grafana container version to 9.4.3
- Updated jsonnet to latest version with binary for linux
This new version can be verified here: 
http://dittybopper-dittybopper.apps.mrnd-gr.bcgo.s1.devshift.org/?orgId=1

Bump grafana version to 9.4.3

---

templates/ocp-performance.jsonnet

Fixes #54
Grafana panels sort ascending by default.
This is terrible default behavior, requiring countless, pointless clicks, and this can be simply fixed with sortDesc!
- Closes #54

sortDesc on all panels

---

templates/General/ocp-performance.jsonnet

In bug https://bugzilla.redhat.com/show_bug.cgi?id=1951877 
Memory consumption keeps growing day by day for "/system.slice" (only on Master nodes)
In 2 days graph it shoot to more than 1G of memory consumption from 500MB aprox.
This pr adds a new Metrics to monitor this metrics:
"sum by(node) (container_memory_rss{id="/system.slice"})"
https://issues.redhat.com/browse/OCPQE-17527

add container_memory_rss system.slice

---

dittybopper/deploy.sh

Added some debugs to check the dittybopper deployment status and containers logs for easy debugging.
https://redhat-internal.slack.com/archives/C020CKMP6CT/p1698249942353429
Tested in local by setting a smaller timeout
```
Waiting for dittybopper deployment to be available...
error: timed out waiting for the condition on deployments/dittybopper
NAME                          READY   STATUS              RESTARTS   AGE
dittybopper-5d7cf58cf-cbb8t   0/2     ContainerCreating   0          3s
NAME          READY   UP-TO-DATE   AVAILABLE   AGE
dittybopper   0/1     1            0           3s
Error from server (BadRequest): container "dittybopper-syncer" in pod "dittybopper-5d7cf58cf-cbb8t" is waiting to start: ContainerCreating
```

Adding debugs when dittybopper deployment fails

---

templates/General/hypershift-performance.jsonnet

Node CPU and memory per HC
Suricata CPU and memory per HC serving node
- Closes #

Added serving node metrics

---

assets/k8s-netperf/panels.libsonnet
assets/k8s-netperf/queries.libsonnet
assets/k8s-netperf/variables.libsonnet
templates/CPT/k8s-netperf-v2.jsonnet

Adding a new variable, compare by, to be used on the new graphs, to compare results by UUID, cluster Name, or OCP Version
Adding a table at the top with global information about the execution selected, like
Adding bar graphs for comparing results between one or more executions, with the information we provide on the result reports, like:
Node to Node
Pod to Pod
Pod to Pod via service
- Closes #

Add workload summary and compare data graphs on k8s-netperf

---

assets/vegeta-wrapper/panels.libsonnet
assets/vegeta-wrapper/queries.libsonnet
assets/vegeta-wrapper/variables.libsonnet
templates/General/vegeta-wrapper-v2.jsonnet

Adding vegeta-wrapper dashboard to grafonnet
- Closes #

Adding vegeta-wrapper dashboard to grafonnet

---

assets/uperf/panels.libsonnet
assets/uperf/queries.libsonnet
assets/uperf/variables.libsonnet
templates/General/uperf-v2.jsonnet

Adding Public - UPerf Results dashboard to grafonnet.
- Closes #

Adding Public - UPerf Results dashboard to grafonnet.

---

.github/workflows/release.yml
Makefile

Migrating dashboards to v2 Version
- Closes #
``` bash 
[smanda performance-dashboards]$  make build-syncer-image v2 push-syncer-image
mkdir -p bin rendered
Downloading jsonnet binary
curl -s -L https://github.com/google/go-jsonnet/releases/download/v0.20.0/go-jsonnet_0.20.0_Linux_x86_64.tar.gz | tar xz -C bin
Downloading jb binary
curl -s -L https://github.com/jsonnet-bundler/jsonnet-bundler/releases/latest/download/jb-linux-amd64 -o bin/jb
chmod +x bin/jb
Downloading vendor files
cd templates && ../bin/jb install && cd ../
GET https://github.com/grafana/grafonnet/archive/9e217263ac4b922ca2e00bc5cc36ada2311bb5a6.tar.gz 200
GET https://github.com/grafana/grafonnet/archive/9e217263ac4b922ca2e00bc5cc36ada2311bb5a6.tar.gz 200
GET …
```

Migrating dashboards to v2 Version

---

assets/ocp-performance/queries.libsonnet
assets/ovn-monitoring/queries.libsonnet
templates/General/ocp-performance.jsonnet
templates/General/ovn-dashboard.jsonnet

This PR updates to **ovnkube_controller_pod_creation_latency_seconds_bucket** from **ovnkube_master_pod_creation_latency_seconds_bucket**
- Closes #

Update to ovnkube_controller_pod_creation_latency_seconds_bucket

---

assets/kube-burner-report-mode/panels.libsonnet
assets/kube-burner-report-mode/queries.libsonnet
assets/kube-burner-report-mode/variables.libsonnet
templates/CPT/kube-burner-report-mode-v2.jsonnet

Adding Kube-burner report mode Dashboard to grafonnet.
- Closes #

Adding Kube-burner report mode Dashboard

---

Makefile
assets/ocp-performance/panels.libsonnet
assets/ocp-performance/queries.libsonnet
assets/ocp-performance/variables.libsonnet
assets/ovn-monitoring/queries.libsonnet
templates/General/ocp-performance.jsonnet
templates/General/ovn-dashboard.jsonnet

Adding a new section to the OCP Performance dashboard that help me get an quick overview of the cluster for any nodes or issues to dive into.
Reordered OVN Dashboard for relevance, but also because the panels pop out of the row.
Also removed old metrics.
Makefile changes to allow generated dashboard cleanup without deleting and redownloading binaries.
variables changes to be more flexible with prometheus that may not be running inside an openshift cluster.
I run `make` and import the generated dashboards in a grafana running locally against a locally running prometheus.

Node panels

---

assets/etcd-on-cluster-dashboard/panels.libsonnet
assets/etcd-on-cluster-dashboard/queries.libsonnet
assets/etcd-on-cluster-dashboard/variables.libsonnet
templates/General/etcd-on-cluster-dashboard.jsonnet

Adding new representations etcd histogram metrics that have proved useful.
Having an etcd pod picker allows us to filter out an individual pod, but with includeAll pulls in all options by default.

Etcd panels

---

assets/etcd-on-cluster-dashboard/panels.libsonnet
assets/etcd-on-cluster-dashboard/queries.libsonnet
templates/General/etcd-on-cluster-dashboard.jsonnet

Fixes a two panels that are empty on recent releases.
Adds a row of panels that can be helpful in finding issues related to large amount of disk and memory activity.
Ran `make`, import generated dashboards into local grafana.

Add panels for compact, defrag, and page faults.
